### ISSUE TITLE
Wrap applying of migrations in a transaction

### ISSUE THREAD

**Issue by vjik** [yiisoft/yii-db-migration#119]
See https://github.com/yiisoft/yii2/blob/8032cbdb4305cb853d538edd8fddd272dd21c9b3/framework/db/Migration.php#L110-L159

We can make this via add special option `--safe` to console commands `migrate/up` and `migrate/down`

**Comment by samdark** [comment]
The option sounds alright but I am a bit concerned since many backends do not support transactions properly for migrations purpose. For example, MySQL automatically commits a transaction after and DDL query.

**Comment by olegbaturin** [comment]
+1 for this feature. This works fine in yii2. Why not to keep safeUp() and safeDown() methods.

**Comment by samdark** [comment]
I think this is must have and there's no point not to use transaction.
