### ISSUE TITLE
Bug on migration tool when creating fields with type "double"

### ISSUE THREAD

**Issue by awesomeguy3** [yiisoft/yii-db-migration#24]
Using php 7.0 and MariaDB. 

When creating a migration that contains fields of type "double", I normally used the function $this->double() which takes one parameter. That one parameter is precision, but when I entered any number or a string, or array of numbers (length and precision), it never set neither length nor precision in my DBMS. 

In MariaDB, I'm defining some field like DOUBLE(10, 2) where first number represents the length, and second number represents number of decimals, but I cannot define it in Yii2 migration with $this->double() function.

**Comment by terabytesoftw** [comment]
https://github.com/yiisoft/db/blob/63d9f8eac9caa1cb4d9493cfe7c2ca5a78ff4e50/src/Schema/SchemaBuilderTrait.php#L183

Fixed.
