### ISSUE TITLE
suggestion : store migration unique id instead of migration full class name in migration table

### ISSUE THREAD

**Issue by jomonkj** [yiisoft/yii-db-migration#26]
Migration namespace will change when splitting app/modules into modules/sub modules/extensions. 

example 

Migrations Ids are like ::tableName() in ActiveRecord

`createPostTable`,
`modifyPostTable`

`core\migration\xxxxxCreatePostTable`
`core\migration\xxxxxModifyPostTable`
when spliting or moving it will change into
`\modules\post\migration\xxxxxCreatePostTable`
`\modules\post\core\migration\xxxxxModifyPostTable`
that will make duplicate migrations

**Comment by terabytesoftw** [comment]
now save the full namespace `Yii\Extension\User\Migration\M200601191317CreateUserTable`.
