### ISSUE TITLE
Identify revertible migrations

### ISSUE THREAD

**Issue by SamMousa** [yiisoft/yii-db-migration#31]
Not all migrations can be reverted.
It would be great to specify for a migration (via an interface) if it is revertible.
Advantage of making this explicit is that we can check this before doing the migration.

Scenarios where this could be interesting are things like automatic deployments, migrations that are revertible require a different level of care vs migrations that cannot be reverted.

A simple solution would be to:

- Split `MigrationInterface` into `MigrationInterface` and `RevertibleMigrationInterface`
- Add a `migrate/safe` command that only migrates revertible migrations.

**Comment by SamMousa** [comment]
Yeah sure.

From a data point of view migrations are either destructive or non-destructive. Adding a column is non-destructive, it can break your app but not your data.
Removing a column is destructive, you cannot (simply) restore it.

Knowing the difference between these in advance can be very important. Automated deployments might want to do full backups before destructive operations, but be less careful with non-destructive ones.

Or maybe you do not want destructive migrations to ever run unattended (where non-destructive ones could be run by non-engineers using some interface).

**Comment by SamMousa** [comment]
Oops, missclick.

**Comment by samdark** [comment]
1. Already done: https://github.com/yiisoft/yii-db-migration/blob/master/src/MigrationInterface.php#L24
2-4. Not sure it is a good idea. For example, you are dropping a column from a table with a 5K records. PHP won't be able to serialize that and DB would likely won't be able store it in a single row. This backup strategy varies very much depending on the project, its data and the way it is stored.

There was an idea about `change()`: https://github.com/yiisoft/yii2/pull/14524 Do you mean something like that?

> The idea is to just provide a very simple API and allow users to benefit.

As far as I see it, you need to mark certain migrations with a custom interface and "hook" into beforeUp/afterUp/beforeDown/afterDown events. Correct?

**Comment by SamMousa** [comment]
> Do you mean something like that?

No, this issue is not about migrations that can be automatically identified to be revertible, like create table would have an inverse which is drop table.

  

> As far as I see it, you need to mark certain migrations with a custom interface and "hook" into beforeUp/afterUp/beforeDown/afterDown events. Correct?

I think we need to have only `up` in the migration interface, since it is the only required one. You can then add extend the interface to be `Revertible` by adding the `Revertible` interface which contains the `down()` method.

All of this is mostly about risk assessment, currently the console can tell me if there are migrations to be done, but there is no way to know if they can be reverted if the application doesn't work as expected after migrating. This is very important to know; for example if I just a have a few minutes but the migration is safe, I might be comfortable deploying a release, knowing that rollback is easy.
If it is not easy because some information is lost then I want to reserve a maintenance window and take extra measures (like a creating an additional point in time backup).

```php
interface Migration {
    public function up(MigrationHelper $h): void;
}
interface Revertible extends Migration {
    public function down(MigrationHelper $h): void;
}
```

>  PHP won't be able to serialize that and DB would likely won't be able store it in a single row. This backup strategy varies very much depending on the project, its data and the way it is stored.

I agree, but we could offer the option to store data, even if its limited. That way people could implement it with their own strategy, pseudocode:

```php
interface Migration {
    public function up(MigrationHelper $h): \JsonSerializable|array;
}
interface Revertible extends Migration {
    public function down(MigrationHelper $h, array $data): void;
}

class Migration1 implements Revertible {
    public function up(MigrationHelper $h): \JsonSerializable|array;
    {
        // Do a backup
        $hash = createMagicTableBackup('x');
        $h->dropTable('x');
        return ['hash' = >$hash];
    }

    public function down(MigrationHelper $h, array $data): void
    {
        restoreMagicTableBackup($data['hash'], 'x');
    }
}

```

The idea here is to expose the functionality in a way that is simple for us while allowing powerful processes to be supported. So what you want to store is up to you, FYI, data columns can easily hold large quantities of data, it will just be hard to query and slower.
But since the migration table is something we control we can simply make sure we don't query the data field during things like generating history overviews.
While in production the table is not used so performance is not that relevant.

If you have a `LONGBLOB` field you can store up to 4gb, PHP will not like that, but I can imagine data sizes of < 50MB would work fine, and cover a large % of use cases.

**Comment by samdark** [comment]
I like the idea of `Revertible` interface. That part is certainly worth implementing.

**Comment by SamMousa** [comment]
Yeah I agree that that part is more objectively good design, whereas the other feature could be argued against.

**Comment by SamMousa** [comment]
> The idea about returning data is more controversial.

Should I create a separate issue where we discuss and gather more feedback? Or would you prefer to just ignore it for now :)

**Comment by samdark** [comment]
Separate issue is better.

**Comment by samdark** [comment]
Interface part done. @SamMousa how would migrate/safe supposed to work? Apply all migrations that are safe and stop on first unsafe one with an error?

**Comment by SamMousa** [comment]
I think it should do all safe and stop before any unsafe. Consider this an unattended upgrade, so unsafe operations have no place here and should be done manually

**Comment by SamMousa** [comment]
Of course on error you have no choice but to stop ; you can't even revert without knowing more about, like idempotency of up and down.

**Comment by samdark** [comment]
Reopened since the original idea was to mark "safe" migrations that, when reverted, do not destroy data.

**Comment by SamMousa** [comment]
The interfaces are fine as far as I can tell from a quick scan on mobile phone.. Just the templates having the interface need to be checked. Note that it is still a devs responsibility to mark the migration appropriately; nothing stops me from marking a drop database as revertible

**Comment by samdark** [comment]
If you see it this way then yes. I just prefer to have "create table" revertible.
