### ISSUE TITLE
Remove dependencies

### ISSUE THREAD

**Issue by xepozz** [yiisoft/yii-db-migration#33]
Would be nice to remove `yii-console` and `view` dependencies.
I think this package will more flexible if these packages will be removed.
If we need console commands for our yii applications we can make third package for integration db-migrations <- yii-db-migrations <- application

Who thinks about this?

**Comment by xepozz** [comment]
For example it can be nice GUI to manage of migrations

**Comment by samdark** [comment]
Would that remove the need for console? I don't think so. Would that remove the need to render templates? Not really.

**Comment by xepozz** [comment]
Ok, yiisoft/view can be saved

**Comment by samdark** [comment]
Same about console, right?

**Comment by xepozz** [comment]
No, in this case console is just adapter

**Comment by samdark** [comment]
If it will be ever used without console, we'll think about it again.
