### ISSUE TITLE
Usage of WebView

### ISSUE THREAD

**Issue by Mister-42** [yiisoft/yii-db-migration#76]
### What steps will reproduce the problem?
Running yii with yii-db-migration installed
`./vendor/bin/yii`

Migration is loading WebView with console config.

### What is the expected result?
List of yii commands

### What do you get instead?
```
In ProxyTrait.php line 20:
                                                        
  No definition for Yiisoft\Router\UrlMatcherInterface
```

### Additional info

| Q                | A
| ---------------- | ---
| Version          | dev
| PHP version      | 8.0.0
| Operating system |

**Comment by samdark** [comment]
View should be used instead.

**Comment by yiiliveext** [comment]
And also we have to move WebView config from common.php to web.php and create View config in console.php in the view package
