### ISSUE TITLE
More abstract unique constraint with null columns in postgres, ms sql

### ISSUE THREAD

**Issue by RodrigoDornelles** [yiisoft/yii-db-migration#99]
### What steps will reproduce the problem?

```PHP
$this->addColumn('users', 'pass_reset_token', $this->string(256)->unique();
```

inserting or updateing two registers whiout 'some_column' value

### What is the expected result?

suport null values in unique constraint

### What do you get instead?
```
nique violation: 7 ERROR: duplicate key value violates unique constraint "pass_reset_token"
DETAIL: Key (email)=() already exists.
```
### Additional info

| Q                | A |
| ---------------- | --- |
| Version | 2.0.42.1 |
| Pgsql Version  | 13.3 |
| PHP version      | 7.4.18 |
| Operating system | Centos 7.9 |

**Comment by darkdef** [comment]
From docs SQL Server:
"Unlike PRIMARY KEY constraints, UNIQUE constraints allow for the value NULL. However, as with any value participating in a UNIQUE constraint, only one null value is allowed per column. A UNIQUE constraint can be referenced by a FOREIGN KEY constraint."

https://docs.microsoft.com/en-us/sql/relational-databases/tables/unique-constraints-and-check-constraints?view=sql-server-ver15

**Comment by darkdef** [comment]
For your case - try trick with calculated field.

**Comment by RodrigoDornelles** [comment]
> For your case - try trick with calculated field.

Yes, I solved it this way, I'm just suggesting that it be something implicit.

**Comment by darkdef** [comment]
It's not a migration task.

**Comment by samdark** [comment]
Closing since it goes against SQL.
